export default {
  Affix: '固定',
  Button: '按钮',
  Cascader: '级联选择器',
  Checkbox: '多选框',
  Collapse: '折叠面板',
  Confirm: '确认框',
  // 'CustomRender': '自定义渲染',
  DatePicker: '时间选择器',
  Dropdown: '下拉菜单',
  Form: '表单',
  Image: '图片',
  Input: '输入框',
  Icon: '图标',
  Modal: '模态窗',
  Navbar: '导航',
  Pagination: '分页',
  Popper: '提示',
  Radio: '单选框',
  ScrollContainer: '滚动条',
  Select: '下拉选择器',
  Slider: '滑块',
  Sidenav: '侧边栏导航',
  Steps: '步骤条',
  Table: '表格',
  Tabs: '标签页',
  Tag: '标签',
  Textarea: '文本框',
  Toast: '轻提示',
  Switch: '选择',
  Transfer: '穿梭框',
  Upload: '上传',
}
