export { default as Close } from './Close.vue'
export { default as Info } from './Info.vue'
export { default as Success } from './Success.vue'
export { default as Warning } from './Warning.vue'
export { default as Notice } from './Notice.vue'
